import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";
import { env } from "../../env.js";

/**
 * Runs pending drizzle-kit migrations (from ./drizzle, generated by
 * `pnpm db:generate`), then applies RLS policies. Use a single, non-pooled
 * connection for migrations.
 */
async function main() {
  const migrationClient = postgres(env.migrateDatabaseUrl, { max: 1 });
  const migrationDb = drizzle(migrationClient);

  console.log("Running migrations...");
  await migrate(migrationDb, { migrationsFolder: "./drizzle" });
  console.log("Migrations applied.");

  await migrationClient.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
