/**
 * Nhóm 5 — Vận hành. See docs/10-module-operations.md and docs/12-database-schema.md.
 */
import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  date,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { branches, buildings, floors, rooms, beds } from "./org-permissions.js";
import { customers } from "./tenancy.js";
import { expenses, invoices } from "./finance.js";
import { id, money } from "./_shared.js";

export const maintenanceTickets = pgTable("maintenance_tickets", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  buildingId: uuid("building_id").references(() => buildings.id),
  floorId: uuid("floor_id").references(() => floors.id),
  roomId: uuid("room_id").references(() => rooms.id),
  bedId: uuid("bed_id").references(() => beds.id),
  assetId: uuid("asset_id").references((): AnyPgColumn => assets.id),
  ticketNo: text("ticket_no").notNull(),
  category: text("category").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  attachments: text("attachments").array(),
  priority: text("priority").notNull().default("NORMAL"),
  slaResponseDeadline: timestamp("sla_response_deadline", { withTimezone: true }),
  slaResolveDeadline: timestamp("sla_resolve_deadline", { withTimezone: true }),
  slaBreached: boolean("sla_breached").notNull().default(false),
  slaBreachedAt: timestamp("sla_breached_at", { withTimezone: true }),
  pausedDurationMinutes: integer("paused_duration_minutes").notNull().default(0),
  reportedBy: uuid("reported_by"),
  reporterType: text("reporter_type"),
  reportedAt: timestamp("reported_at", { withTimezone: true }).notNull().defaultNow(),
  assignedTo: uuid("assigned_to"),
  assignedBy: uuid("assigned_by"),
  assignedAt: timestamp("assigned_at", { withTimezone: true }),
  startedAt: timestamp("started_at", { withTimezone: true }),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  closedAt: timestamp("closed_at", { withTimezone: true }),
  resolution: text("resolution"),
  resolutionAttachments: text("resolution_attachments").array(),
  laborCost: money("labor_cost"),
  partsCost: money("parts_cost"),
  totalCost: money("total_cost"),
  chargeToTenant: boolean("charge_to_tenant").notNull().default(false),
  chargedInvoiceId: uuid("charged_invoice_id").references(() => invoices.id),
  expenseId: uuid("expense_id").references(() => expenses.id),
  status: text("status").notNull().default("OPEN"),
  mergedIntoTicketId: uuid("merged_into_ticket_id"),
  tenantRating: integer("tenant_rating"),
  tenantFeedback: text("tenant_feedback"),
}, (t) => ({
  ticketNoUnique: uniqueIndex("maintenance_tickets_ticket_no_key").on(t.ticketNo),
}));

export const ticketEvents = pgTable("ticket_events", {
  id: id(),
  ticketId: uuid("ticket_id").notNull().references(() => maintenanceTickets.id),
  branchId: uuid("branch_id").notNull(),
  eventType: text("event_type").notNull(),
  fromStatus: text("from_status"),
  toStatus: text("to_status"),
  by: uuid("by"),
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  note: text("note"),
  attachments: text("attachments").array(),
});

export const assets = pgTable("assets", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  buildingId: uuid("building_id").references(() => buildings.id),
  floorId: uuid("floor_id").references(() => floors.id),
  roomId: uuid("room_id").references(() => rooms.id),
  bedId: uuid("bed_id").references(() => beds.id),
  assetCode: text("asset_code").notNull(),
  qrCode: text("qr_code"),
  name: text("name").notNull(),
  category: text("category"),
  brand: text("brand"),
  model: text("model"),
  serialNumber: text("serial_number"),
  locationType: text("location_type").notNull().default("ROOM"),
  purchaseDate: date("purchase_date"),
  purchasePrice: money("purchase_price"),
  supplier: text("supplier"),
  warrantyUntil: date("warranty_until"),
  depreciationMethod: text("depreciation_method"),
  usefulLifeMonths: integer("useful_life_months"),
  currentBookValue: money("current_book_value"),
  condition: text("condition").notNull().default("NEW"),
  status: text("status").notNull().default("IN_USE"),
  repairCount: integer("repair_count").notNull().default(0),
  totalRepairCost: money("total_repair_cost").notNull().default(sql`0`),
  images: text("images").array(),
  notes: text("notes"),
}, (t) => ({
  branchAssetCodeUnique: uniqueIndex("assets_branch_id_asset_code_key").on(t.branchId, t.assetCode),
}));

export const assetEvents = pgTable("asset_events", {
  id: id(),
  assetId: uuid("asset_id").notNull().references(() => assets.id),
  branchId: uuid("branch_id").notNull(),
  eventType: text("event_type").notNull(),
  at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
  by: uuid("by"),
  fromLocation: text("from_location"),
  toLocation: text("to_location"),
  cost: money("cost"),
  note: text("note"),
  ticketId: uuid("ticket_id").references(() => maintenanceTickets.id),
  attachments: text("attachments").array(),
});

export const housekeepingTasks = pgTable("housekeeping_tasks", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  roomId: uuid("room_id").notNull(),
  bedId: uuid("bed_id"),
  taskType: text("task_type").notNull(),
  assignedTo: uuid("assigned_to"),
  dueAt: timestamp("due_at", { withTimezone: true }),
  status: text("status").notNull().default("PENDING"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  completedBy: uuid("completed_by"),
  photos: text("photos").array(),
  issuesFound: text("issues_found"),
});

export const houseRules = pgTable("house_rules", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  version: text("version").notNull(),
  effectiveFrom: date("effective_from").notNull(),
  effectiveTo: date("effective_to"),
  sections: jsonb("sections").$type<unknown[]>(),
  penaltyRules: jsonb("penalty_rules").$type<unknown[]>(),
  status: text("status").notNull().default("DRAFT"),
  publishedAt: timestamp("published_at", { withTimezone: true }),
  publishedBy: uuid("published_by"),
}, (t) => ({
  branchVersionUnique: uniqueIndex("house_rules_branch_id_version_key").on(t.branchId, t.version),
}));

export const violations = pgTable("violations", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  customerId: uuid("customer_id").notNull().references(() => customers.id),
  roomId: uuid("room_id"),
  violationNo: text("violation_no").notNull(),
  ruleCode: text("rule_code"),
  ruleVersion: text("rule_version"),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  reportedBy: uuid("reported_by"),
  description: text("description"),
  evidence: text("evidence").array(),
  severity: text("severity"),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  penaltyType: text("penalty_type"),
  penaltyAmount: money("penalty_amount"),
  status: text("status").notNull().default("DRAFT"),
  approvedBy: uuid("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  chargedInvoiceId: uuid("charged_invoice_id").references(() => invoices.id),
  tenantAcknowledgedAt: timestamp("tenant_acknowledged_at", { withTimezone: true }),
  appealReason: text("appeal_reason"),
  appealResolution: text("appeal_resolution"),
}, (t) => ({
  violationNoUnique: uniqueIndex("violations_violation_no_key").on(t.violationNo),
}));

export const visitorLogs = pgTable("visitor_logs", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  visitorType: text("visitor_type").notNull(),
  visitorName: text("visitor_name").notNull(),
  visitorPhone: text("visitor_phone"),
  visitorIdNumber: text("visitor_id_number"),
  hostCustomerId: uuid("host_customer_id").references(() => customers.id),
  roomId: uuid("room_id"),
  purpose: text("purpose"),
  checkInAt: timestamp("check_in_at", { withTimezone: true }).notNull().defaultNow(),
  checkOutAt: timestamp("check_out_at", { withTimezone: true }),
  recordedBy: uuid("recorded_by"),
  approvedByHost: boolean("approved_by_host").notNull().default(false),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  vehiclePlate: text("vehicle_plate"),
  overnightStay: boolean("overnight_stay").notNull().default(false),
  notes: text("notes"),
});

export const staffShifts = pgTable("staff_shifts", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  staffId: uuid("staff_id").notNull(),
  date: date("date").notNull(),
  shiftType: text("shift_type").notNull(),
  startTime: text("start_time"),
  endTime: text("end_time"),
  status: text("status").notNull().default("SCHEDULED"),
  actualStartAt: timestamp("actual_start_at", { withTimezone: true }),
  actualEndAt: timestamp("actual_end_at", { withTimezone: true }),
  note: text("note"),
}, (t) => ({
  staffDateUnique: uniqueIndex("staff_shifts_staff_id_date_key").on(t.staffId, t.date),
}));
