/**
 * Nhóm 2 — Khách thuê & Lưu trú. See docs/12-database-schema.md.
 *
 * `contracts` vs `bed_assignments` is the single most important modelling
 * decision in the system — see docs/11-architecture.md §2 D2 and
 * docs/13-erd.md §2 before touching this file.
 */
import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { branches, beds, rooms } from "./org-permissions.js";
import { auditColumns, deletedAt, id, money } from "./_shared.js";

export const customers = pgTable("customers", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  customerCode: text("customer_code").notNull(),
  fullName: text("full_name").notNull(),
  dateOfBirth: date("date_of_birth"),
  gender: text("gender").notNull(),
  idType: text("id_type"),
  idNumber: text("id_number"),
  idIssueDate: date("id_issue_date"),
  idIssuePlace: text("id_issue_place"),
  phone: text("phone"),
  phoneHistory: text("phone_history").array(),
  email: text("email"),
  zaloPhone: text("zalo_phone"),
  permanentAddress: jsonb("permanent_address"),
  hometown: text("hometown"),
  emergencyContact: jsonb("emergency_contact"),
  secondaryContact: jsonb("secondary_contact"),
  payer: jsonb("payer").$type<{ name?: string; phone?: string; relationship?: string; bankAccount?: string }>(),
  occupation: text("occupation"),
  school: text("school"),
  company: text("company"),
  studentId: text("student_id"),
  photo: text("photo"),
  idFrontImage: text("id_front_image"),
  idBackImage: text("id_back_image"),
  otherDocuments: jsonb("other_documents").$type<unknown[]>(),
  currentBranchId: uuid("current_branch_id"),
  currentRoomId: uuid("current_room_id"),
  currentBedId: uuid("current_bed_id"),
  currentContractId: uuid("current_contract_id"),
  creditBalance: money("credit_balance").notNull().default(0n),
  status: text("status").notNull().default("PROSPECT"),
  isBlacklisted: boolean("is_blacklisted").notNull().default(false),
  blacklistReason: text("blacklist_reason"),
  blacklistedAt: timestamp("blacklisted_at", { withTimezone: true }),
  temporaryResidenceStatus: text("temporary_residence_status").notNull().default("NOT_REGISTERED"),
  source: text("source"),
  preferences: text("preferences"),
  internalNotes: text("internal_notes"),
  mergedIntoCustomerId: uuid("merged_into_customer_id"),
  anonymizedAt: timestamp("anonymized_at", { withTimezone: true }),
  ...auditColumns,
  deletedAt: deletedAt(),
}, (t) => ({
  orgCustomerCodeUnique: uniqueIndex("customers_org_id_customer_code_key").on(t.orgId, t.customerCode),
  orgIdNumberUnique: uniqueIndex("customers_org_id_id_number_key").on(t.orgId, t.idNumber),
}));

export const bookings = pgTable("bookings", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  bookingNo: text("booking_no").notNull(),
  customerId: uuid("customer_id").notNull().references(() => customers.id),
  bedId: uuid("bed_id").references(() => beds.id),
  roomId: uuid("room_id").references(() => rooms.id),
  expectedCheckInDate: date("expected_check_in_date"),
  expectedDurationMonths: integer("expected_duration_months"),
  quotedPrice: money("quoted_price"),
  depositRequired: money("deposit_required"),
  depositPaid: money("deposit_paid").notNull().default(0n),
  holdUntil: timestamp("hold_until", { withTimezone: true }).notNull(),
  status: text("status").notNull().default("NEW"),
  source: text("source"),
  roommatePreferences: text("roommate_preferences"),
  cancelReason: text("cancel_reason"),
  cancelledBy: uuid("cancelled_by"),
  cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
  contractId: uuid("contract_id"),
  notes: text("notes"),
  ...auditColumns,
  deletedAt: deletedAt(),
}, (t) => ({
  bookingNoUnique: uniqueIndex("bookings_booking_no_key").on(t.bookingNo),
}));

export const contracts = pgTable("contracts", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  contractNo: text("contract_no").notNull(),
  version: integer("version").notNull().default(1),
  customerId: uuid("customer_id").notNull().references(() => customers.id),
  coTenantIds: uuid("co_tenant_ids").array(),
  guardianInfo: jsonb("guardian_info"),
  wholeRoom: boolean("whole_room").notNull().default(false),
  bedIds: uuid("bed_ids").array().notNull().default([]),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
  durationMonths: integer("duration_months"),
  autoRenewMonthly: boolean("auto_renew_monthly").notNull().default(false),
  noticePeriodDays: integer("notice_period_days").notNull().default(30),
  monthlyRent: money("monthly_rent").notNull(),
  depositAmount: money("deposit_amount").notNull().default(0n),
  depositMonths: integer("deposit_months"),
  billingCycle: text("billing_cycle").notNull().default("MONTHLY"),
  billingDayOfMonth: integer("billing_day_of_month"),
  dueDayOfMonth: integer("due_day_of_month"),
  electricityPrice: money("electricity_price"),
  waterPrice: money("water_price"),
  includedServiceIds: uuid("included_service_ids").array(),
  discounts: jsonb("discounts").$type<unknown[]>(),
  templateId: uuid("template_id"),
  termsSnapshot: text("terms_snapshot").notNull(),
  specialTerms: text("special_terms"),
  houseRulesVersion: text("house_rules_version"),
  status: text("status").notNull().default("DRAFT"),
  approvedBy: uuid("approved_by"),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
  terminatedAt: timestamp("terminated_at", { withTimezone: true }),
  terminationReason: text("termination_reason"),
  terminationType: text("termination_type"),
  bookingId: uuid("booking_id").references(() => bookings.id),
  previousContractId: uuid("previous_contract_id"),
  nextContractId: uuid("next_contract_id"),
  signatureMethod: text("signature_method"),
  signedAt: timestamp("signed_at", { withTimezone: true }),
  ...auditColumns,
  deletedAt: deletedAt(),
}, (t) => ({
  contractNoUnique: uniqueIndex("contracts_contract_no_key").on(t.contractNo),
}));

/** ★ The most important table in the system — see module doc comment above. */
export const bedAssignments = pgTable("bed_assignments", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  contractId: uuid("contract_id").notNull().references(() => contracts.id),
  customerId: uuid("customer_id").notNull().references(() => customers.id),
  bedId: uuid("bed_id").notNull().references(() => beds.id),
  roomId: uuid("room_id").notNull().references(() => rooms.id),
  floorId: uuid("floor_id").notNull(),
  buildingId: uuid("building_id").notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date"),
  reason: text("reason").notNull(),
  dailyRate: money("daily_rate").notNull(),
  monthlyRate: money("monthly_rate").notNull(),
  transferReason: text("transfer_reason"),
  previousAssignmentId: uuid("previous_assignment_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  createdBy: uuid("created_by"),
}, (t) => ({
  // ★ Chống bán trùng giường ở tầng database — chỉ 1 assignment đang mở/giường.
  oneOpenAssignmentPerBed: uniqueIndex("bed_assignments_one_open_per_bed")
    .on(t.bedId)
    .where(sql`${t.endDate} IS NULL`),
}));

export const checkinCheckoutRecords = pgTable("checkin_checkout_records", {
  id: id(),
  orgId: uuid("org_id").notNull(),
  branchId: uuid("branch_id").notNull().references(() => branches.id),
  type: text("type").notNull(),
  contractId: uuid("contract_id").notNull().references(() => contracts.id),
  customerId: uuid("customer_id").notNull().references(() => customers.id),
  bedId: uuid("bed_id").notNull().references(() => beds.id),
  roomId: uuid("room_id").notNull().references(() => rooms.id),
  assignmentId: uuid("assignment_id").notNull().references(() => bedAssignments.id),
  performedAt: timestamp("performed_at", { withTimezone: true }).notNull().defaultNow(),
  performedBy: uuid("performed_by"),
  checklist: jsonb("checklist").$type<unknown[]>(),
  assetInventory: jsonb("asset_inventory").$type<unknown[]>(),
  photos: text("photos").array().notNull().default([]),
  keysHandedOver: jsonb("keys_handed_over").$type<unknown[]>(),
  utilityReadings: jsonb("utility_readings"),
  damages: jsonb("damages").$type<unknown[]>(),
  tenantSignature: text("tenant_signature"),
  staffSignature: text("staff_signature"),
  notes: text("notes"),
});
